### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by GreenRover** [disconnect/apache-websocket#35]
Hi, when i try to use the websocket with high traffic then i get a segmentation fault.

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/apache2 -k start'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f72d5207e02 in apr_bucket_free () from /usr/lib/libaprutil-1.so.0

(gdb) 

I compiled and tested it again an "Apache/2.4.6" and "Apache/2.4.9"

Do you have any ideas hot to where the problem is?

**Comment by jchampio** [comment]
I know it's been over a year, but by any chance are you using HTTPS? I have seen high-traffic segfaults when using mod_ssl, which I believe are fixed by [this pull request](https://github.com/disconnect/apache-websocket/pull/41). I've forked the repo and applied that patch here: https://github.com/jchampio/apache-websocket

**Comment by GreenRover** [comment]
Hi thanks for answer. no i dont, i use a reverse proxy for https termination, it is simple ws no wss.
But after no response and no solution for this issue i decidet not longer to use this apache module.

**Comment by jchampio** [comment]
Okay, thanks for the reply! I'll try to add some high-traffic testing to the fork eventually and see if I can flush out any problems.

**Comment by GreenRover** [comment]
Very out dated
